USE gym_management;
SET FOREIGN_KEY_CHECKS=0;

-- Drop foreign keys first to allow modifying columns
ALTER TABLE member DROP FOREIGN KEY member_ibfk_1;

ALTER TABLE trainer MODIFY Trainer_ID INT AUTO_INCREMENT;
ALTER TABLE workout_plan MODIFY Workout_ID INT AUTO_INCREMENT;
ALTER TABLE diet_plan MODIFY Diet_ID INT AUTO_INCREMENT;
ALTER TABLE BODY_MEASUREMENT MODIFY Measurement_ID INT AUTO_INCREMENT;
ALTER TABLE attendance MODIFY Attendance_ID INT AUTO_INCREMENT;
ALTER TABLE payment MODIFY Payment_ID INT AUTO_INCREMENT;

ALTER TABLE member ADD CONSTRAINT member_ibfk_1 FOREIGN KEY (Trainer_ID) REFERENCES trainer (Trainer_ID);

SET FOREIGN_KEY_CHECKS=1;
