USE gym_management;
SET FOREIGN_KEY_CHECKS=0;

-- Update trainer table
ALTER TABLE member DROP FOREIGN KEY fk_trainer;
ALTER TABLE trainer MODIFY Trainer_ID INT AUTO_INCREMENT;
ALTER TABLE member ADD CONSTRAINT fk_trainer FOREIGN KEY (Trainer_ID) REFERENCES trainer (Trainer_ID);

-- Update other tables to AUTO_INCREMENT
ALTER TABLE workout_plan MODIFY Workout_ID INT AUTO_INCREMENT;
ALTER TABLE diet_plan MODIFY Diet_ID INT AUTO_INCREMENT;
ALTER TABLE BODY_MEASUREMENT MODIFY Measurement_ID INT AUTO_INCREMENT;
ALTER TABLE attendance MODIFY Attendance_ID INT AUTO_INCREMENT;
ALTER TABLE payment MODIFY Payment_ID INT AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS=1;
